version: "3.3"

services:
  shop:
    image: shop-front
    container_name: shop-front
    build:
      context: ./shop-front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email romanets2003@bk.ru -d yanre.ru --agree-tos