version: "3.3"

services:
  shop:
    image: shop-front
    container_name: shop-front
    build:
      context: ./shop-front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email romanets2003@bk.ru -d yanre.ru --agree-tos
  db:
    image: 'postgres:13.3'
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: "data"
    ports:
      - "5432:5432"
  app:
    build: ./shop
    container_name: app
    ports:
      - "8090:8090"
    depends_on:
      - db